### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by alexadkins** [city-of-baltimore/ridesystems#12]
Do you guys have any documentation on usage?

Thanks!

**Comment by cylussec** [comment]
There is documentation in the code, with each of the functions documented, and there is the tests which kind of show how to use it, but there is not complete documentation because this was just something I built to interface with our Ridesystems portal. Ridesystems is absolutely awful to work with so you are not going to get much in the way of official documentation, but I am happy to help you get started!

**Comment by alexadkins** [comment]
Just a tip for which scripts to look at to use your python functionality would be great. Thanks!

**Comment by alexadkins** [comment]
Nevermind, I found your tests. Thanks a bunch! I'm looking to just export predicted bus times vs. actual arrival times, so hopefully these tools will help me out.

**Comment by cylussec** [comment]
The predicted bus times should be from the GTFS file (unless you are looking at the predictions that they provide ahead of time). If you are looking for the real time data, you probably want to look at the api.py (although there might be issues with the API... I think I tried something recently and saw odd data... the integration tests I have are not great). If you want to see the data afterwards (like what you would get from the reports), then use the reports.py. It basically scrapes the website for the data and returns it. 

This is not the most rigorously tested code, so let me know if you have issues. Happy to help, especially if you can contribute to the project (including the documentation 😂).
